import Foundation

/// Faithful port of the star simulation in Windows 2000 `ssstars.scr`
/// ("Starfield Simulation", 5.00.2195.6601).
///
/// Every constant here was recovered by disassembling `bin/ssstars.scr`;
/// see docs/NOTES.md for the address of each one. The integer math is reproduced
/// exactly, including truncating division, so motion matches the original.
struct StarfieldEngine {

    // MARK: Constants lifted from the binary

    /// 0xA00. Both the Z of a freshly spawned star and the projection scale,
    /// which is why a new star lands exactly on its random screen position.
    static let zFar = 2560
    /// 0x280. Star edge length is (zFar - z) / 640 + 1, i.e. 1...5.
    static let sizeDivisor = 640
    /// SetTimer(hwnd, 1, 50, NULL) -> 20 ticks/sec.
    static let tickInterval = 0.050

    static let minDensity = 10, maxDensity = 200, defaultDensity = 25
    static let minWarp = 0, maxWarp = 10, defaultWarp = 5

    /// The original ramps toward (WarpSpeed + 1) * 10, so 10...110.
    static func targetSpeed(forWarp warp: Int) -> Int { (warp + 1) * 10 }

    struct Star { var x = 0, y = 0, z = StarfieldEngine.zFar }

    // MARK: State

    private(set) var stars: [Star] = []
    private(set) var width = 0
    private(set) var height = 0

    /// Current speed, which eases toward `target` by one unit per star per
    /// tick -- the ramp lives inside the per-star loop in the original.
    private var speed = 0
    private var target = StarfieldEngine.targetSpeed(forWarp: StarfieldEngine.defaultWarp)

    /// MSVC rand() state. Seeded from the system RNG rather than the fixed 1
    /// the CRT uses, so two launches do not draw the same sky. Pass an explicit
    /// seed to make a run reproducible -- the SVG illustrations rely on this so
    /// they can be regenerated byte-for-byte and checked for drift.
    private var seed: UInt32

    init(seed: UInt32? = nil) {
        self.seed = seed ?? UInt32.random(in: .min ... .max)
    }

    private var centerX: Int { width / 2 }
    private var centerY: Int { height / 2 }

    // MARK: Configuration

    var warpSpeed = StarfieldEngine.defaultWarp {
        didSet { target = StarfieldEngine.targetSpeed(forWarp: warpSpeed) }
    }

    mutating func configure(width: Int, height: Int, density: Int) {
        let count = min(max(density, Self.minDensity), Self.maxDensity)
        let resized = (width != self.width || height != self.height)
        self.width = width
        self.height = height

        if stars.count != count {
            stars = Array(repeating: Star(), count: count)
            respawnAll()
        } else if resized {
            respawnAll()
        }
    }

    private mutating func respawnAll() {
        for i in stars.indices { respawn(i) }
    }

    // MARK: Simulation

    /// One 50 ms tick: ease the speed, pull every star toward the viewer, and
    /// recycle any that reach the eye or leave the screen.
    mutating func step() {
        guard width > 0, height > 0, !stars.isEmpty else { return }

        for i in stars.indices {
            if speed < target { speed += 1 } else if speed > target { speed -= 1 }

            stars[i].z -= speed
            if stars[i].z < 0 { stars[i].z = 0 }
            // z == 0 would divide by zero on the next projection, so the
            // original respawns here rather than clamping to 1.
            if stars[i].z == 0 { respawn(i) }

            let p = project(stars[i])
            if p.x < 0 || p.y < 0 || p.x > width || p.y > height { respawn(i) }
        }
    }

    /// Perspective divide. Truncating integer division is deliberate: it is
    /// what gives the original its slightly steppy motion near the center.
    func project(_ star: Star) -> (x: Int, y: Int, size: Int) {
        (x: star.x * Self.zFar / star.z + centerX,
         y: star.y * Self.zFar / star.z + centerY,
         size: (Self.zFar - star.z) / Self.sizeDivisor + 1)
    }

    /// Drop a star back at the far plane on a random screen-space ray.
    private mutating func respawn(_ i: Int) {
        // The original tests the width twice -- the Y branch included. Keeping
        // the quirk costs nothing and both fall back to the center anyway.
        if width != 0 && height != 0 {
            stars[i].x = rand16() % width - centerX
            stars[i].y = rand16() % height - centerY
        } else {
            stars[i].x = 0
            stars[i].y = 0
        }
        stars[i].z = Self.zFar
    }

    /// The Visual C++ runtime's rand(), inlined into the screen saver.
    private mutating func rand16() -> Int {
        seed = seed &* 0x343FD &+ 0x269EC3
        return Int((seed >> 16) & 0xFFFF)
    }
}
